import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

// eslint-disable-next-line import/no-unassigned-import
import './globals.css';
import { Providers } from './providers';

import { Header } from '@/components/Header';
import { Flex } from '@chakra-ui/react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Flex direction="column" minHeight="100vh" align={"center"}>
            <Header />
            {children}
          </Flex>
        </Providers>
      </body>
    </html>
  );
}
